POLLS_RELEASE_SEED= 1496047114
POLLS_TESTING_SEED= 596837685
AUTHOR_ID  = R3DEY
SERVICE_ID = 00001
CFLAGS      = -Os -g -Werror -Wno-overlength-strings -Wno-packed
include /usr/share/cb-testing/cgc-cb.mk
